# Generated by Django 5.2.4 on 2025-07-08 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่องาน')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'รออนุมัติ'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('COMPLETED', 'เสร็จสิ้น'), ('REJECTED', 'ปฏิเสธ')], default='PENDING_APPROVAL', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ปฏิเสธ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ร้องขอ')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่องานย่อย')),
                ('status', models.CharField(choices=[('PENDING', 'รอทำ'), ('COMPLETED', 'เสร็จสิ้น')], default='PENDING', max_length=50)),
                ('object_id', models.PositiveIntegerField(help_text='ID ของ object เป้าหมาย')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(help_text='โมเดลเป้าหมาย (เช่น CustomerProfile, Vehicle)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
            ],
        ),
    ]
